/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gr.cons.elst;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertLinesMatch;

class ElstTest {

    @Test
    void test_one() {
        assertEquals("αυρ", Elst.lowerStopAndStep("Αύριο"));
    }

    @Test
    void test_phrase() {
        String text = "Πέτσας-Κορωνοϊός: Σε lockdown Θεσσαλονίκη και Σέρρες από αύριο - Με SMS οι μετακινήσεις";
        List<String> stemmed = Arrays.stream(text.split(" "))
                .map(Elst::lowerStopAndStep)
                .collect(Collectors.toList());
        assertLinesMatch(List.of("πετσ", "Σε", "lockdown", "θεσσαλον", "και", "σερρ", "από", "αυρ", "-",
                "Με", "sms", "οι", "μετακινησ"), stemmed);
    }

}
